export enum Genre {
  POP = 'POP',
  ROCK = 'ROCK',
  HIPHOP = 'HIPHOP',
  ELECTRONIC = 'ELECTRONIC',
  JAZZ = 'JAZZ',
  CLASSIC = 'CLASSIC',
  COUNTRY = 'COUNTRY',
  METAL = 'METAL',
  BLUES = 'BLUES',
  RAP = 'RAP',
  REGGAE = 'REGGAE',
  FOLK = 'FOLK',
  PUNK = 'PUNK',
  DISCO = 'DISCO',
  HOUSE = 'HOUSE',
  TECHNO = 'TECHNO',
  TRANCE = 'TRANCE',
  DUBSTEP = 'DUBSTEP',
  DRUMNBASS = 'DRUMNBASS',
  DANCE = 'DANCE',
  SOUL = 'SOUL',
  FUNK = 'FUNK',
  RNB = 'RNB',
  INDIE = 'INDIE',
  KPOP = 'KPOP',
  JPOP = 'JPOP',
  VPOP = 'VPOP',
}

export const GenreArr = [
  'POP',
  'ROCK',
  'HIPHOP',
  'ELECTRONIC',
  'JAZZ',
  'CLASSIC',
  'COUNTRY',
  'METAL',
  'BLUES',
  'RAP',
  'REGGAE',
  'FOLK',
  'PUNK',
  'DISCO',
  'HOUSE',
  'TECHNO',
  'TRANCE',
  'DUBSTEP',
  'DRUMNBASS',
  'DANCE',
  'SOUL',
  'FUNK',
  'RNB',
  'INDIE',
  'KPOP',
  'JPOP',
  'VPOP',
];
