export enum Genre {
  POP = 'pop',
  ROCK = 'rock',
  HIPHOP = 'hiphop',
  ELECTRONIC = 'electronic',
  JAZZ = 'jazz',
  CLASSIC = 'classic',
  COUNTRY = 'country',
  METAL = 'metal',
  BLUES = 'blues',
  RAP = 'rap',
  REGGAE = 'reggae',
  FOLK = 'folk',
  PUNK = 'punk',
  DISCO = 'disco',
  HOUSE = 'house',
  TECHNO = 'techno',
  TRANCE = 'trance',
  DUBSTEP = 'dubstep',
  DRUMNBASS = 'drumnBass',
  DANCE = 'dance',
  SOUL = 'soul',
  FUNK = 'funk',
  RNB = 'rnb',
  INDIE = 'indie',
  KPOP = 'kpop',
  JPOP = 'jpop',
  VPOP = 'vpop',
}

export const GenreArr = [
  'pop',
  'rock',
  'hiphop',
  'electronic',
  'jazz',
  'classic',
  'country',
  'metal',
  'blues',
  'rap',
  'reggae',
  'folk',
  'punk',
  'disco',
  'house',
  'techno',
  'trance',
  'dubstep',
  'drumnBass',
  'dance',
  'soul',
  'funk',
  'rnb',
  'indie',
  'kpop',
  'jpop',
  'vpop',
];
